/**
 * Servicio Clientes Kallsonys
 * Servicio para la gestión de clientes en  OMS Kallsonys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Direcciones } from './direcciones';
import { StatusType } from './statusType';


/**
 * clientes.
 */
export interface DireccionesRsType { 
    status?: StatusType;
    direcciones?: Direcciones;
}
