export * from './cliente';
export * from './clienteRsType';
export * from './clientes';
export * from './clientesRsType';
export * from './direccion';
export * from './direcciones';
export * from './direccionesRsType';
export * from './postRsType';
export * from './statusType';
