/**
 * Servicio Reportes Kallsonys
 * Servicio para generar reportes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoriaRsType } from './categoriaRsType';
import { StatusType } from './statusType';


/**
 * Categorias.
 */
export interface CategoriasRsType { 
    status?: StatusType;
    categorias?: CategoriaRsType;
}
