/**
 * Servicio Reportes Kallsonys
 * Servicio para generar reportes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Cliente { 
    idcliente?: number;
    usuario?: string;
    password?: string;
    apellido?: string;
    nombre?: string;
    telefono?: string;
    email?: string;
    estado?: string;
    categoria?: string;
    tipoidentificacion?: string;
    numeroidentificacion?: string;
}
