/**
 * Servicio Reportes Kallsonys
 * Servicio para generar reportes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClienteRsType } from './clienteRsType';
import { StatusType } from './statusType';


/**
 * Clientes.
 */
export interface ClientesRsType { 
    status?: StatusType;
    clientes?: ClienteRsType;
}
