/**
 * Servicio Reportes Kallsonys
 * Servicio para generar reportes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrdenRsType } from './ordenRsType';
import { StatusType } from './statusType';


/**
 * Ordenes.
 */
export interface OrdenesRsType { 
    status?: StatusType;
    ordenes?: OrdenRsType;
    orden?: OrdenRsType[];
}
