/**
 * Servicio Reportes Kallsonys
 * Servicio para generar reportes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Orden2RsType } from './orden2RsType';
import { StatusType } from './statusType';


/**
 * Ordenes.
 */
export interface Ordenes2RsType { 
    status?: StatusType;
    ordenes?: Orden2RsType;
    orden?: Orden2RsType[];
}
