/**
 * Servicio Ordenes Kallsonys
 * Servicio para la gestión de ordenes en  OMS Kallsonys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Status de respuesta.
 */
export interface StatusType { 
    /**
     * Código de status.
     */
    statusCode?: number;
    /**
     * Descripción de estatus.
     */
    statusDesc?: string;
}
