/**
 * Servicio Ordenes Kallsonys
 * Servicio para la gestión de ordenes en  OMS Kallsonys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DetalleOrden } from './detalleOrden';
import { OrdenM } from './ordenM';


/**
 * información de devuelta.
 */
export interface ParametrosDeSalidaType { 
    ordenes?: Array<OrdenM>;
    detalles?: Array<DetalleOrden>;
}
