/**
 * Servicio roles Kallsonys
 * Servicio para la gestión de roles en  OMS Kallsonys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Roles } from './roles';
import { StatusType } from './statusType';


/**
 * Respuesta genérica.
 */
export interface RolRsType { 
    status?: StatusType;
    datosBasicos?: Array<Roles>;
}
