/**
 * Categoria Productos Kallsonys
 * Categoria Productos Kallsonys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParamSalidaTypeCategoria } from './paramSalidaTypeCategoria';
import { StatusType } from './statusType';


/**
 * Respuesta genérica.
 */
export interface CategoriaRsType { 
    status?: StatusType;
    categoria?: ParamSalidaTypeCategoria;
}
