/**
 * Servicio Campañas Kallsonys
 * Servicio para la gestión de campañas en  OMS Kallsonys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Campañas de la plataforma Kallsonys
 */
export interface Campana { 
    idCamapana?: number;
    descripcion?: string;
    fechaInicio?: string;
    fechaFin?: string;
    usuarioCreador?: string;
    fechaCreacion?: string;
    rutaBanner?: string;
    idProducto?: number;
}
