/**
 * Servicio Campanas Kallsonys
 * Servicio para la gestión de Campanas en  OMS Kallsonys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Campana { 
    idCamapana?: number;
    descripcion?: string;
    fechaInicio?: Date;
    fechaFin?: Date;
    usuarioCreador?: string;
    fechaCreacion?: Date;
    rutaBanner?: string;
    idProducto?: number;
    estado?: string;
    nombreProducto?: string;
}